### ISSUE TITLE
Clipmenu takes in VI commands from terminal

### ISSUE THREAD

**Issue by nictrix** [naotaka/ClipMenu#19]
Hi, I have used ClipMenu for a couple years now and love it.  Thanks for making such a great desktop tool.  Recently on the latest version of MAC OS 10.10.4 I began having problems with VI commands and ClipMenu.  For example:

Go to terminal > edit a file `vi .bash_profile` > delete a line using these vi commands `dd` or `d$` > go to ClipMenu and you'll see the line's content in clipboard history

Can I fix this in the preferences?

**Comment by jpmoral** [comment]
@nictrix
I use ClipMenu as well.  There is an "Exclude Applications" setting in the Preferences' General tab.

**Comment by nictrix** [comment]
@jpmoral I wish it was that easy..which if you do that then this won't happen.  But I'd like it to go back to how it was before..something happened..not really sure what.  I use my terminal more than anything on my Mac OS and I'd like to still use ClipMenu for it.  Thanks for reach out and suggesting something, appreciate it.

**Comment by jpmoral** [comment]
Sorry I misunderstood it to be something trivial.  Can you describe what the expected behavior is and what you're actually seeing?  I'm curious, and we might find something in the source.

**Comment by nictrix** [comment]
What happened before some update, I guess on Mac OS was you could do VI commands in a text file on the terminal and not have ClipMenu copy the text you are manipulating with those commands. (the commands stated in the original message here)

**Comment by tthayer** [comment]
This is because of functionality within vim that sends yanked buffer content to the system pasteboard. I personally find it very useful, but a simple google search for "OSX vim paste" should show you the .vimrc snippet that is setting up this behavior.

**Comment by nictrix** [comment]
Ahh these makes sense on why it was happening on one computer, but not the other. Thanks @tthayer
