### ISSUE TITLE
update to Xcode >3 ?

### ISSUE THREAD

**Issue by tessus** [naotaka/ClipMenu#4]
I was wondering, if you plan to update the code base so that it can be compiled on systems which are newer than 6 years old.

I'd like to add a few features, but unfortunately there are 2 IB plugin dependencies, which I can't resolve with my Xcode 5.

**Comment by naotaka** [comment]
Sorry for the inconvenience.

But fortunately, @nacika-ins is updating the code to be able to compile with Xcode 6 Beta 4. If you are interested in it, watch his fork: 

https://github.com/nacika-ins/ClipMenu

I'll merge his work when I receive his pull request.

**Comment by tessus** [comment]
Thanks for the info. I'm looking forward to seeing it compile with recent Xcode versions.

**Comment by tessus** [comment]
@naotaka any update on this? it seems that this project is dead and replaced by the Swift version.

Unfortunately the Swift code is not available, so I cannot even help coding and add the features I was looking for. Can I assume that ClipMenu 1.0 will not be open source?

**Comment by antoniwan** [comment]
Hello @tessus. This project is succeeded here: https://github.com/Clipy/Clipy
